base_url = "https://jalsol.github.io"
theme = "no-style-please"
description = "just a little spark of light."
compile_sass = false
build_search_index = false
generate_feed = false

[markdown]
highlight_code = true
extra_syntaxes_and_themes = ["highlight_themes"]
highlight_theme = "catppuccin-latte"
external_links_target_blank = true
lazy_async_image = true

[extra]
author = "Quang-Truong Nguyen"
logo = "images/hanabi_pfp.jpg"
list_pages = false
twitter_card = false

header_nav = [
    { name = "~home", url = "/" },
    { name = "*blogs", url = "/blog" },
]

