base_url = "https://jalsol.github.io"
compile_sass = false
build_search_index = false
theme = "no-style-please"
author = "Quang-Truong Nguyen"

[markdown]
highlight_code = true
extra_syntaxes_and_themes = ["highlight_themes"]
highlight_theme = "catppuccin-latte"
external_links_target_blank = true
lazy_async_image = true

[extra]
list_pages = false
twitter_card = false

header_nav = [
    { name = "~home", url = "/" },
    { name = "*blogs", url = "/blog" },
]

